# Generated by Django 4.0 on 2022-07-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
