# Generated by Django 4.0 on 2022-07-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
