# Generated by Django 4.0 on 2022-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_active_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('int', models.IntegerField()),
            ],
        ),
    ]
